[package]
name = "evcxr"
version = "0.9.0"
license = "Apache-2.0"
description = "An Evaluation Context for Rust"
repository = "https://github.com/google/evcxr"
readme = "README.md"
authors = ["The Evcxr Authors"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
tempfile = "3.1.0"
libc = "0.2.80"
json = "0.12.4"
regex = { version = "1.5.5", default-features = false, features = [ "std" ] }
once_cell = "1.5.2"
libloading = "0.7.0"
backtrace = "0.3.35"
dirs = "3.0.1"
which = "4.0.2"
evcxr_input = "1.0.0"
ra_ap_ide = "=0.0.45"
ra_ap_ide_db = "=0.0.45"
ra_ap_project_model = "=0.0.45"
ra_ap_paths = "=0.0.45"
ra_ap_vfs = "=0.0.45"
ra_ap_vfs-notify = "=0.0.45"
ra_ap_hir = "=0.0.45"
ra_ap_base_db = "=0.0.45"
ra_ap_syntax = "=0.0.45"
unicode-segmentation = "1.7.1"
# TODO: Remove the following. It's just here to prevent a build failure that occurs in ra_ap_syntax
# when we get pre.5.
rowan = "=0.13.0-pre.3"

[target.'cfg(all(unix, not(target_os = "freebsd")))'.dependencies]
sig = "1.0.0"

[target.'cfg(target_os = "macos")'.dependencies]
filetime = "0.2.13"
